# Generated by Django 4.2.18 on 2025-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
