# Generated by Django 4.2.18 on 2025-01-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
