# Generated by Django 4.2.18 on 2025-01-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('actioned', models.BooleanField(default=False)),
                ('actioned_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
