# Generated by Django 4.2.18 on 2025-01-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportdetails_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='reports.report'),
        ),
    ]
