# Generated by Django 4.2.18 on 2025-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_date_posted_actionmessage_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
